import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="main">
          <div className="view">
            <div>
              <Header />
              <div className="content">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
